import pygame

FPS = 60

#DADOS BASE TELA
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 900


#DADOS BASE DO JOGADOR
PLAYER_WIDTH = 100
PLAYER_HEIGHT = 100
PLAYER_SPD = 500     #ESTOU TRABALHANDO COM PIXEL
PLAYER_HP = 3
PLAYER_STARTING_X = (SCREEN_WIDTH // 2) - (PLAYER_WIDTH // 2)
PLAYER_STARTING_Y = SCREEN_HEIGHT - PLAYER_HEIGHT - 50
PLAYER_IMAGE_PATH = "assets/imagens/jogador_nave.png"
PLAYER_IMAGE = None

#DADOS BASE DO TIRO
BULLET_WIDTH = 10
BULLET_HEIGHT = 20
BULLET_SPD = 600
BULLET_STARTING_X = PLAYER_STARTING_X
BULLET_STARTING_Y = PLAYER_HEIGHT - (PLAYER_HEIGHT // 2)

#DADOS BASE DOS INIMIGOS METEORO
METEOR_WIDTH = 150
METEOR_HEIGHT = 150
METEOR_SCALE = 1.25
METEOR_HP = 1
METEOR_DAMAGE = 1
METEOR_SPD = 200
METEOR_FRAMES = []